apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-db
  namespace: bloodhoundad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-db
  template:
    metadata:
      labels:
        app: graph-db
    spec:
      containers:
      - name: neo4j
        image: docker.io/library/neo4j:4.4
        env:
        - name: NEO4J_AUTH
          value: "neo4j/bloodhoundcommunityedition"
        - name: NEO4J_dbms_allow__upgrade
          value: "true"
        ports:
        - containerPort: 7687
        - containerPort: 7474
        livenessProbe:
          exec:
            command:
            - wget
            - -O
            - /dev/null
            - -q
            - http://localhost:7474
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
     # volumes:
     # - name: neo4j-data
     #   persistentVolumeClaim:
     #     claimName: graph-db-neo4j-data-pvc
