apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloodhound
  namespace: bloodhoundad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bloodhound
  template:
    metadata:
      labels:
        app: bloodhound
    spec:
      containers:
      - name: bloodhound
        image: docker.io/specterops/bloodhound:latest
        env:
        - name: bhe_disable_cypher_qc
          value: "false"
        ports:
        - containerPort: 8080
      # Uncomment the following if you have a custom configuration file
      # volumes:
      # - name: bloodhound-config
      #   configMap:
      #     name: bloodhound-config
