apiVersion: v1
kind: Service
metadata:
  name: app-db 
  namespace: bloodhoundad
spec:
  selector:
    app: bloodhound-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
