namespace: bloodhoundad

app-db:
  name: bloodhound-postgres
  replicas: 1
  appName: bloodhound-postgres
  container:
    name: postgres
    image: docker.io/library/postgres:13.2
    env:
      POSTGRES_USER: "bloodhound"
      POSTGRES_PASSWORD: "bloodhoundcommunityedition"
      POSTGRES_DB: "bloodhound"
    ports:
      containerPort: 5432
  livenessProbe:
    user: bloodhound
    database: bloodhound
    port: "5432"
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  service:
    enabled: true
    type: ClusterIP
    port: 5432
    targetPort: 5432
  volumes:
    pvcEnabled: true  # Set to false to disable PVC
    persistentVolumeClaim:
      claimName: bloodhound-postgres-pvc
      size: "1Gi"  # Configurable storage size

graph-db:
  name: graph-db
  replicas: 1
  appName: graph-db
  container:
    name: neo4j
    image: docker.io/library/neo4j:4.4
    env:
      NEO4J_AUTH: "neo4j/bloodhoundcommunityedition"
      NEO4J_dbms_allow__upgrade: "true"
    ports:
      - containerPort: 7687
      - containerPort: 7474
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  volumes:
    pvcEnabled: true  # Set to false to disable PVC
    persistentVolumeClaim:
      claimName: graph-db-neo4j-data-pvc
      size: "1Gi"  # Configurable storage size
