apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.graph-db.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  replicas: {{ .Values.graph-db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.graph-db.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.graph-db.appName }}
    spec:
      containers:
      - name: {{ .Values.graph-db.container.name }}
        image: {{ .Values.graph-db.container.image }}
        env:
        - name: NEO4J_AUTH
          value: {{ .Values.graph-db.container.env.NEO4J_AUTH }}
        - name: NEO4J_dbms_allow__upgrade
          value: {{ .Values.graph-db.container.env.NEO4J_dbms_allow__upgrade }}
        ports:
        - containerPort: {{ .Values.graph-db.container.ports[0].containerPort }}
        - containerPort: {{ .Values.graph-db.container.ports[1].containerPort }}
        livenessProbe:
          exec:
            command:
            - wget
            - -O
            - /dev/null
            - -q
            - http://localhost:7474
          initialDelaySeconds: {{ .Values.graph-db.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.graph-db.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.graph-db.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.graph-db.livenessProbe.failureThreshold }}
        {{- if .Values.graph-db.volumes.pvcEnabled }}
        volumeMounts:
        - name: neo4j-data
          mountPath: /var/lib/neo4j/data
        {{- end }}
      {{- if .Values.graph-db.volumes.pvcEnabled }}
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: {{ .Values.graph-db.volumes.persistentVolumeClaim.claimName }}
      {{- end }}
