apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bloodhound-postgres-pvc
  namespace: bloodhoundad
  metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
