apiVersion: v1
kind: Service
metadata:
  name: app-db 
  namespace: bloodhoundad
  metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  selector:
    app: bloodhound-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
