{{- if .Values.app-db.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: app-db
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.app-db.service.type }}
  ports:
    - port: {{ .Values.app-db.service.port }}
      targetPort: {{ .Values.app-db.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.app-db.appName }}
{{- end }}
