apiVersion: v1
kind: Service
metadata:
  name: graph-db
  namespace: bloodhoundad
  metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  selector:
    app: graph-db
  ports:
  - name: bolt
    protocol: TCP
    port: 7687
    targetPort: 7687
  - name: http
    protocol: TCP
    port: 7474
    targetPort: 7474
  type: ClusterIP
