{{- if .Values.graph-db.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.graph-db.name }}-service
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  selector:
    app: {{ .Values.graph-db.appName }}
  ports:
    {{- range .Values.graph-db.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  type: {{ .Values.graph-db.service.type }}
{{- end }}
